# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.demo.hostName }}
  namespace: {{ .Release.Namespace }}
  annotations: {{- include "openmatch.chartmeta" . | nindent 4 }}
  labels:
    app: {{ template "openmatch.name" . }}
    component: demo
    release: {{ .Release.Name }}
spec:
  selector:
    app: {{ template "openmatch.name" . }}
    component: demo
  type: {{ coalesce .Values.global.kubernetes.service.portType .Values.demo.portType }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.demo.httpPort }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.demo.hostName }}
  namespace: {{ .Release.Namespace }}
  annotations: {{- include "openmatch.chartmeta" . | nindent 4 }}
  labels:
    app: {{ template "openmatch.name" . }}
    component: demo
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.demo.replicas }}
  selector:
    matchLabels:
      app: {{ template "openmatch.name" . }}
      component: demo
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      annotations:
        {{- include "openmatch.chartmeta" . | nindent 8 }}
      labels:
        app: {{ template "openmatch.name" . }}
        component: demo
        release: {{ .Release.Name }}
    spec:
      volumes:
        {{- include "openmatch.volumes.configs" . | nindent 8}}
        {{- include "openmatch.volumes.tls" . | nindent 8}}
      serviceAccountName: {{ .Values.global.kubernetes.serviceAccount }}
      containers:
      - name: {{ .Values.demo.hostName }}
        volumeMounts:
          {{- include "openmatch.volumemounts.configs" . | nindent 10 }}
          {{- include "openmatch.volumemounts.tls" . | nindent 10 }}
        image: "{{ .Values.global.image.registry }}/{{ .Values.demo.image}}:{{ .Values.global.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.demo.httpPort }}
        {{- include "kubernetes.probe" (dict "port" .Values.demo.httpPort) | nindent 8 }}
