# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
appVersion: "0.8.0-rc.1"
version: 0.8.0-rc.1
name: open-match
description: Flexible, extensible, and scalable video game matchmaking.
keywords:
  - kubernetes
  - game-development
  - multiplayer
  - matchmaking
  - go
  - golang
home: https://open-match.dev
sources:
  - https://github.com/googleforgames/open-match
maintainers:
 - name: open-match
   email: open-match-discuss@googlegroups.com
   url: https://groups.google.com/forum/#!forum/open-match-discuss
engine: gotpl
icon: https://open-match.dev/site/images/logo.svg
tillerVersion: ">2.10.0"
