# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for open-match-demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

demo:
  hostName: om-demo
  httpPort: 51507
  portType: ClusterIP
  replicas: 1
  image: openmatch-demo-first-match

image:
  registry: gcr.io/open-match-public-images
  tag: 0.0.0-dev
  pullPolicy: Always

# TODO: Split tls configs into a separate config file. For now Open Match assumes core components share the same secure mode
# with the mmfs and evaluator, so we have to copy these secure settings and define a new configmap for it whenever we what 
# to create a new evaluator and mmf. We should create a global configmap for the security settings for all subcharts 
# under the /install/helm/open-match directory to avoid copy&paste files around.
configs:
  demo-configmap:
    mountPath: /app/config/om
    volumeName: demo-config-volume
